### ISSUE TITLE
Number of platforms 0

### ISSUE THREAD

**Issue by xonobo** [JacekDanecki/neo-hub#1]
I builded the docker for ubuntu 16.04 and run the docker but clinfo gives zero device. I call the docker enviroment like this

docker run -ti neo-16.04

I guess more options are needed to reach the host devices. Can you help me in setting the docker options?

**Comment by xonobo** [comment]
solved by calling 
docker run --device /dev/dri:/dev/dri -ti neo-16.04

**Comment by xonobo** [comment]
I tried to run this docker on a host machine with opencl 1.2 beignet. Calling clinfo in the docker gives zero platforms. What is the problem?

**Comment by AlbertoMQ** [comment]
did you figure it out?
