### ISSUE TITLE
Add libze_loader?

### ISSUE THREAD

**Issue by maleadt** [JacekDanecki/neo-hub#4]
Following https://github.com/intel/compute-runtime/issues/319#issuecomment-635939207, the images now provide `libze_intel_gpu`, but don't have `libze_loader` (or the validation layer). Could you add those as well?

**Comment by JacekDanecki** [comment]
Commit e2b716f4231c409cff918ce8975edfb0078a7f80 added Level Zero loader. Docker images were updated.

**Comment by maleadt** [comment]
Ouch, sorry for the dup (of myself).
