### ISSUE TITLE
Alpine Please?

### ISSUE THREAD

**Issue by Odianosen25** [JacekDanecki/neo-hub#5]
Please can an image be created based on Alpine Linux?

Kind regards

**Comment by JacekDanecki** [comment]
It's on my TODO list.

**Comment by Odianosen25** [comment]
@JacekDanecki thanks kind sir for the replay, will await it then.

Regards

**Comment by Odianosen25** [comment]
@JacekDanecki good evening and hope you good? I am sorry for asking, but pls any headway on this issue?

Or on the other hand, can I be led in the right direction on how to build it myself, if possible?

Kind regards
